version: "3.9"

services:  
  database:
    image: mongo:latest
    container_name: database
    env_file: 
      - .env 
    ports:
      - 27017:27017
    volumes: 
     - dbdata-volume:/data/db
    environment:
      - MONGO_INITDB_USERNAME: ${DB_USER}
      - MONGO_INITDB_DATABASE: ${DB_HOST}
      - MONGO_INITDB_PASSORD: ${DB_PASS}
  app:
    build: .
    container_name: webmotorsclone
    restart: always   
    ports:
      - 3333:3333
    volumes: 
       - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
    dbdata-volume:
        driver: local