version: "3.9"

services:  
  database:
    image: mongo:latest
    container_name: database
    env_file: 
      - .env 
    ports:
      - "${DB_PORT}:27017"
    volumes: 
        -dbdata-volume:/data/db
    environment:
       MONGO_INITDB_USERNAME: ${DB_USERNAME}
       MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
       MONGO_INITDB_DATABASE: ${DB_DATABASE}

  app:
    build: .
    container_name: webmotorsclone
    restart: always
    env_file: 
      - .env  
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes: 
       - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
    dbdata-volume: